### ISSUE TITLE
No tusd headers

### ISSUE THREAD

**Issue by lgcshy** [fentas/tus-shell-client#9]
I set the TUS_HEADERS
export TUS_HEADERS="Tus-Extension: [creation,creation-with-upload,termination,concatenation,creation-defer-length], Tus-Max-Size: 128849018880,Tus-Version: 1.0.0"
 echo $TUS_HEADERS
Tus-Extension: [creation,creation-with-upload,termination,concatenation,creation-defer-length], Tus-Max-Size: 128849018880,Tus-Version: 1.0.0

when run tus -o  I get an error:  No tusd headers

**Comment by fentas** [comment]
Sorry has been a bit, since I looked into this script.
But `-o` checks `TUS_OPTIONS` env.

`TUS_HEADERS` will be used for the tus requests itself.

So depends what you want to do.

**Comment by lgcshy** [comment]
> Sorry has been a bit, since I looked into this script. But `-o` checks `TUS_OPTIONS` env.
> 
> `TUS_HEADERS` will be used for the tus requests itself.
> 
> So depends what you want to do.

Thanks for your reply, it helps me a lot. However, I currently found another problem. When using tusd's s3store, there is no response from this tool for uploading.

**Comment by lgcshy** [comment]
My problem has been resolved
